### ISSUE TITLE
Incident Level - 13SURF

### ISSUE THREAD

**Issue by bcoyte** [rporteous1/SurfPlus#11]
**Is your feature request related to a problem? Please describe.**
SLSNSW incidents are categorised as level 2 (minimum) for any 13SURFactivations.

**Describe the solution you'd like**
If 13SURF box is ticked Surfcom should only allow a level 2 or 3 to be recorded.

**Describe alternatives you've considered**
A system that includes business rules and data validation as standard.

**Additional context**
If a level 1 incident is later reclassified as 13SURF a validation error/notice should be displayed.
We currently manage this completely outside of Surfcom, our exported data has data validation rules applied. Where validation rules are not met (eg level 1 & 13SURF or level 1 & Deaths >0) then records are identified with an action request. Team members go back to Surfcom, re-open incidents and update information.
Having rules built into our systems saves a substantial amount of re-work and provides higher quality statistics.

**Comment by rporteous1** [comment]
This enhancement has been implemented in v2.3.
