### ISSUE TITLE
Extension icon

### ISSUE THREAD

**Issue by bcoyte** [rporteous1/SurfPlus#2]
Current state: Two extensions with different functionality exist.
Issue: It is difficult to discern which is which.
Suggested outcome: Extensions have different icons.

**Comment by rporteous1** [comment]
Does this suit?
![ezgif-3-4f85aa16cb](https://github.com/rporteous1/SurfPlus/assets/160448581/643c67bb-07ca-4ca8-b637-66edb7318f66)

**Comment by rporteous1** [comment]
Implemented.
