### ISSUE TITLE
Member Injuries

### ISSUE THREAD

**Issue by bcoyte** [rporteous1/SurfPlus#29]
**Is your feature request related to a problem? Please describe.**
Surfcom Management System does not export the Member Injury checkbox to the incident report.
The workaround in place for years has been to use incident type Member Injury, though recent updates to allow multiple incdent types will alleviate some concerns we still have no way to categorise member injuries in the manner required for monthly board reporting. 

**Describe the solution you'd like**
When Member Injury box is ticked then display a drop-down box to ask for incident activity. An operator should be required to select one, this should save to the Brief Description field as this field is mapped to cause of incident field in Surfguards IRD. 

Activity
--
IRB   Operations
IRB Training
IRB Racing
RWC   Operations
RWC Training
Patrol/Bronze   training/proficiency
Surf Sports   Water
Surf Sports   Sand
Surf Sports   Boats
Other/unknown

**Describe alternatives you've considered**
Requests to have this information manually written into further info field have largely been forgotten/overlooked. 
Drop-down menu selections offer a far greater control over formatting and later data extraction.

**Additional context**

**Comment by rporteous1** [comment]
Implemented
