### ISSUE TITLE
Filter page responses

### ISSUE THREAD

**Issue by bcoyte** [rporteous1/SurfPlus#30]
**Is your feature request related to a problem? Please describe.**
Surfcom appends text from the SMS Response Page instructions field to the original message (outgoing) and every single respondents SMS response. This unnecessarily clutters the incident log and makes updates difficult to see.

**Describe the solution you'd like**
For all responses to an SMS page message the log should filter out everything between the "." after ETA response & "Confirmation

Eg: Incident #{{L#########}} - {{Respondent Name}} ({{Mailing Group Name}}) ({{Repondent_mobile}}) is responding to incident. Current location {{location_response}}. ETA {{response_minutes}}. Confirmation via SMS

**Describe alternatives you've considered**
Migrating SLSNSW to Vision5 or similar CAD system that allows users granular control over incident views with comprehensive filters.

**Additional context**

![image](https://github.com/rporteous1/SurfPlus/assets/166900896/541ee4b9-738d-4ef4-aa8f-17e72e617f52)
![Surfplus filter page request](https://github.com/rporteous1/SurfPlus/assets/166900896/d40bc5b1-800e-4a86-b5dd-af268f1dc252)

**Comment by rporteous1** [comment]
Implemented
