### ISSUE TITLE
Service status recording

### ISSUE THREAD

**Issue by bcoyte** [rporteous1/SurfPlus#40]
**Describe the bug**
Services are not recorded to incident as notified when they are notified through the Surfcom Management System

Background: 
When a Service is paged for an Emergency Response, the service/unit is not added to the incident as a responding service. 
This needs to be done manually, often being overlooked because it requires a duplication after paging a Club call out team an operator is required to mark the club as "Notified" using either [Add Unit] or [Add Service] buttons.
Statistics around which clubs responded are also captured manually and Surfcom has no reporting function for this.
In the absence of API access, SLSNSW incident reporting data is obtained by running a Power Automate flow to extract daily comms logs and Incident Reports, this data is transformed in a Power Query to extract relevant elements. Recent updates mean that services responded can be obtained from the incident log meaning operators no longer need to manually record these in a spreadsheet after the fact.
Quality of data captured can be significantly improved by having Surfcom automatically update unit status.

**To Reproduce**
1. Open an incident
2. Select a "SOC DEMO Notifications" Mailing group in Response SMS Notification (Callout SMS) card in SurfPlus
3. Click [Send Response SMS]
4. Click blue link icon beside recipient and submit ETA
5. Return to incident Manager and see corresponding unit status has not updated

**Expected behavior**
- mark service as "Notified" (Status=NO) when paged e.g The Entrance Emergency Call Out Team receives a page SMS, The Entrance added to Responding Services as status Notified.
- mark service as "Enroute" (Status=ER) when member submits an Affirmative response

Exception handling
- member is on multiple call out teams that are paged to the same incident, submitting an affirmative response (adding an ETA) should mark each connected service as responding.

**Comment by rporteous1** [comment]
This has been implemented for Clubs, if DO's, UAV's, RWC's are wanted too, let me know.

**Comment by rporteous1** [comment]
The further functionality will be implemented after 2.14.0, going to push this live now though.
