### ISSUE TITLE
Stats form bug

### ISSUE THREAD

**Issue by bcoyte** [rporteous1/SurfPlus#45]
**Describe the bug**
Completed stats form creates a loop. 
Submitting the form opens the Surfcom Incident in the form window.
Attempts to close the incident result in pop-up reminder to complete stats form. 
Ad infinitum.

**To Reproduce**
1. Submit stats form
2. Try to close job

**Expected behavior**
Less inception, more submitty.
Was working as expected until yesterday.

**Comment by rporteous1** [comment]
Looked into the code, no reason this should be happening, unable to reproduce, spoken to Glenn, he's unable to reproduce either. 

If you run into the issue again, just create a new ticket referencing this issue.

**Comment by rporteous1** [comment]
Looked into the code, no reason this should be happening, unable to reproduce, spoken to Glenn, he's unable to reproduce either. 

If you run into the issue again, just create a new ticket referencing this issue.
