### ISSUE TITLE
Action prompt - Shark Incidents

### ISSUE THREAD

**Issue by bcoyte** [rporteous1/SurfPlus#7]
**Is your feature request related to a problem? Please describe.**
Surfcom Management System lacks any business rules - it cannot prompt actions or next steps in a process. 

**Describe the solution you'd like**
If incident type = "Shark Attack (IRD)" then 
- add a flash banner or other highly visible prompt "DPI Notification required"
- pre-fill mailing group field with selection "00-9 Shark Incident Notification" & relevant Branch Notification group. 
- Shark Incident Notification should be included on both SMS & email notifications generated through the incident.
- action prompt persists until a notification is sent to "00-9 Shark Incident Notification" OR a transmission is recorded from Surfcom to DPI 

**Describe alternatives you've considered**
Action prompts in incidents are compiled on a dashboard or other central location for both operators and SDO to review and triage. Example can be supplied of RFS Incident Management System open incident list displays a column that indicates when next SITREP is due, highlighting overdue SITREPs. Ours could include actions such as Agency notifications required, member welfare referrals outstanding, follow-up tasks assigned for tasking issues/continuity/tech problems/support tickets, overdue SITREPS etc

**Additional context**

**Comment by rporteous1** [comment]
This enhancement has been implemented in v2.3.
