### ISSUE TITLE
Action prompt - MAC notifiable incidents

### ISSUE THREAD

**Issue by bcoyte** [rporteous1/SurfPlus#8]
**Is your feature request related to a problem? Please describe.**
Team sometimes neglect MAC notifications, often choosing to only liaise with Police Radio.
MAC notification is a requirement per the State Rescue Policy.

**Describe the solution you'd like**
IF incident type is any of the following:

- Capsized Vessel (IRD) 
- Diving Accident (IRD) 
- Drowning (IRD) 
- Flare Sighting 
- Missing Person - Water (IRD) 
- Rock Fishing Incident (IRD)
- Missing Vessel (IRD)
- Shark Attack (IRD)

AND informant is not MAC or MACLO
then action prompt/flash banner notification to MACSAR
prompt persists until notification to MACSAR is completed

[MAC Notifiable Incidents 1.0.pdf](https://github.com/rporteous1/SurfPlus/files/15331395/MAC.Notifiable.Incidents.1.0.pdf)

**Describe alternatives you've considered**
Adding ICEMS, long lead time. 
Adopt systems like LIMSOC/Noggin/D4H that support required functions.
Build in required business rules Surfcom Management System does not have natively. 

**Additional context**

**Comment by rporteous1** [comment]
This enhancement has been implemented in v2.3.
